version: '3.8'

services:
  # --- DATABASES AND MESSAGE BROKER ---
  postgres:
    image: postgres:15-alpine
    container_name: pizza_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pizza_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d pizza_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:6-jammy
    container_name: pizza_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: pizza_logs
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: pizza_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: .
      args:
        - APP_NAME=user-service
    container_name: pizza_user_service
    env_file:
      - .env
    command: sh -c "npx prisma migrate deploy && node dist/apps/user-service/main.js"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  pizza-service:
    build:
      context: .
      args:
        - APP_NAME=pizza-service
    container_name: pizza_pizza_service
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  order-service:
    build:
      context: .
      args:
        - APP_NAME=order-service
    container_name: pizza_order_service
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  api-gateway:
    build:
      context: .
      args:
        - APP_NAME=api-gateway
    container_name: pizza_api_gateway
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started
    restart: on-failure

volumes:
  postgres_data:
  mongodb_data:
  rabbitmq_data:
